### ISSUE TITLE
Consider basing unification and reification on walk

### ISSUE THREAD

**Issue by brandonwillard** [pythological/unification#10]
We should consider redesigning this project so that `_unify` and `_reify` are based on a more fundamental generic, lazily-computed `walk` function.  Additional type support could be added by implementing only a specialized `walk` dispatch function for each new type&mdash;instead of both a `_reify` and `_unify`, as is currently the case.

Said `walk` function could, for instance, return a tuple containing the type/constructor and an iterator/generator with it's arguments (e.g. `(list, iter([1, 2]))`) and so on in a recursive fashion.  This way, `reify` could be implemented by applying the type/constructors to the iterator/generators.  In this scenario, `unify` would only need to check the types/constructors and apply the standard condition logic.  The equality check between objects (i.e. `__eq__`) would need to line-up with a type + argument for this kind of unification to be consistent with the current form.
This `walk` could be implemented using `etuple`, or, more specifically, a lazy/generator version of `etuplize` (i.e. that lazily performs deep `etuple` conversion).

An approach like this separates structure traversal from the specific objectives of unification and reification, and that's an advantage for all the standard programming reasons.  More importantly, it makes implementations of functions like `isground` much more efficient, since object traversal wouldn't require (re)construction of the object or elaborate hacks of `unify` and/or the functionality of logic variables&mdash;which is all due to the entanglement between the object walking code and `unify`/`reify`.

Furthermore, with some approach along these lines, we could probably stop relying on the Python stack and avoid the current recursion-bound scaling limits (see https://github.com/pythological/kanren/issues/21).

**Comment by majidaldo** [comment]
will this obviate the need for the unification  library?

**Comment by brandonwillard** [comment]
> will this obviate the need for unification as a library?

No, I believe that the proposed `walk` would likely be the main focus of a revised unification library.

In relation to this issue, I've started using a [generator/coroutine-based queuing approach](https://github.com/pythological/unification/blob/master/unification/core.py#L28) to traversing nested structures.  It avoids the Python recursion limit (in TCO-like fashion) and allows one to short-circuit the traversal. 

It's now being used by `logical-unification` (i.e. my fork of `unification`) to accomplish the goals set in this issue, aside from basing `unify` and `reify` on a single `walk` (per structure type).

The same approach is being [used in `etuples`](https://github.com/pythological/etuples/blob/master/etuples/core.py#L13) to get past recursion limits in `etuple` evaluation and [`etuplization`](https://github.com/pythological/etuples/blob/master/etuples/dispatch.py#L125).

Some of the logic behind this approach is duplicated between `logical-unification` and `etuples`, so that could be fixed; however, I wasn't readily able to base `unify` and `reify` on the same walk function.  It seemed like another abstraction was necessary.

**Comment by majidaldo** [comment]
ya i was getting confused about aligning those projects in my head within kanren.  i explained it to myself by thinking that multipledispatch matching / unification is functionally the python 'language' of etuples and cons.
