### ISSUE TITLE
Error on duplicate pattern

### ISSUE THREAD

**Issue by majidaldo** [pythological/unification#19]
I feel that the following shouldn't be allowed.

```
from unification.match import *
from unification import var
n = var('n')

@match(0)
def fib(n):
    return 0

@match(0)
def fib(n):
    return 'somethingelse'

>>> print(fib(0))
somethingelse
```

**Comment by brandonwillard** [comment]
It looks like the dispatch on `fib` is simply being redefined, and that falls in line with general symbol (i.e. function and/or variable) reassignment in Python.  One should be allowed to redefine functions and/or their dispatches dynamically; it's an expected Python feature, so this library shouldn't unnecessarily restrict that behavior.
