### ISSUE TITLE
Unification does not work with dataclasses by default

### ISSUE THREAD

**Issue by rlouf** [pythological/unification#28]
Unification does not work with dataclasses by default:

```python
from dataclasses import dataclass

@dataclass
class Test():
    a: int
    b: int

test1 = Test(1, 4)
test2 = Test(var(), var())

res = unify(test1, test2)
print(res)
# false
```

But will work if we use the `@unifiable` decorator:

```python
from dataclasses import dataclass
from unification import unifiable

@unifiable
@dataclass
class Test():
    a: int
    b: int

test1 = Test(1, 4)
test2 = Test(var(), var())

res = unify(test1, test2)
print(res)
```

Is there any good reason to not register the unify and reify operations on dataclasses directly in the library? Using dataclasses is very natural when we want to unify on data structures where some of the elements default to a logic variable, as in the following kanren example: https://github.com/pythological/kanren/pull/52

**Comment by brandonwillard** [comment]
Some basic reasons why this wouldn't have been implemented by default for `dataclass`es are given in [this `kanren` discussion](https://matrix.to/#/!QGDbyhrHbxCRKSoFeo:gitter.im/$VDIPvDlpL8O9Lz_lGsr2Ze84xugMK9fAqnMXY2ID0Eg?via=gitter.im&via=matrix.org).

The main reason is that this library is only intended to support the most standard (ordered) Python data structures (e.g. `Sequence` types and ordered `Mapping`s) by default, and not _everything_ that could possibly be made unifiable in the Python standard library.  Everything else can be made easily unifiable, but not by default.

Un-making things unifiable isn't exactly the cleanest operation, so it's always better to let the user/developer decide exactly which non-standard data structures they want to be unifiable&mdash;and how.
