### ISSUE TITLE
Substituting variables in unified expressions

### ISSUE THREAD

**Issue by jarble** [pythological/unification#33]
Does this library have a method to substitute variables in expressions after they have been unified?
It seems that the expressions are unchanged after unification:

```
from unification import *
anti1 = [var("x"),">","4"]
anti2 = ["3",">",var("y")]
unify(anti1,anti2)
print(anti1)
```

This program prints `[~x, '>', '4']`, but I wanted to get `['3', '>', '4']` instead.

**Comment by brandonwillard** [comment]
See `unification.reify`.

**Comment by jarble** [comment]
@brandonwillard Is this function documented anywhere? The README doesn't mention it.

**Comment by brandonwillard** [comment]
It's been added: #34.

**Comment by brandonwillard** [comment]
Nope, here instead: #35.
