### ISSUE TITLE
Update pip package to latest code

### ISSUE THREAD

**Issue by jrabinow** [pythological/unification#40]
```
Traceback (most recent call last):
 [...]
    from .core import unify, reify
  File "[...]/unification/core.py", line 2, in <module>
    from collections import Iterator
ImportError: cannot import name 'Iterator' from 'collections' ([...]/python3.11/collections/__init__.py)
```
According to [this StackOverflow post](https://stackoverflow.com/a/72032097), `collections.Iterator` was removed in python3.10 (great backwards-compatibility policy btw 😆). I went to open a pull request but it seems the changes have already been made, but the pypi package hasn't been updated.

Would it be possible to update the package on pypi?

**Comment by brandonwillard** [comment]
> Would it be possible to update the package on pypi?

Ah, yes, I'll create a new release.  Thanks for the heads-up!

**Comment by brandonwillard** [comment]
OK, done: https://github.com/pythological/unification/releases/tag/v0.4.6.
